[package]
name = "trash-cli"
version = "0.1.0"
authors = ["Brian Shu <littlebubu.shu@gmail.com>"]
description = """
trash-cli written in rust
"""
documentation = "https://github.com/oberblastmeister/trash-cli"
homepage = "https://github.com/oberblastmeister/trash-cli"
repository = "https://github.com/oberblastmeister/trash-cli"
readme = "README.md"
keywords = ["trash", "remove", "recycle", "bin", "freedesktop"]
categories = ["command-line-utilities"]
license = "MIT"
edition = "2018"

[workspace]
members = [
    "crates/lib"
]

[[bin]]
path = "crates/cli/main.rs"
name = "trash"

[dependencies]
trash_lib = { path = "crates/lib" }
structopt = "0.3.17"
lazy_static = "1.4.0"
prettytable-rs = "0.8.0"
log = "0.4.11"
lscolors = "0.7.1"
eyre = "0.6.0"
env_logger = "0.7.1"
ansi_term = "0.12.1"
chrono = "0.4.15"
regex = "1.3.9"
atty = "0.2.14"
terminal_size = "0.1.13"
