[package]
name = "trash-cli"
version = "0.1.0"
authors = ["Brian Shu <littlebubu.shu@gmail.com>"]
edition = "2018"

[workspace]
members = [
    "crates/lib"
]

[[bin]]
path = "crates/cli/main.rs"
name = "trash"

[dependencies]
trash_lib = { path = "crates/lib" }
structopt = "0.3.17"
lazy_static = "1.4.0"
prettytable-rs = "0.8.0"
log = "0.4.11"
lscolors = "0.7.1"
eyre = "0.6.0"
itertools = "0.9.0"
env_logger = "0.7.1"
